/**
 * BugReporter - Create GitHub issues for detected bugs
 *
 * Uses the GitHub CLI (gh) to create issues in either the
 * application repo (for app bugs) or the agent repo (for self-improvement).
 */

import { exec } from 'child_process';
import { promisify } from 'util';
import type { DetectedBug } from '../agent/types.js';

const execAsync = promisify(exec);

export interface ReporterConfig {
  appRepo: string; // e.g., "consciousfounders/oblique"
  agentRepo: string; // e.g., "consciousfounders/probe"
  createIssues: boolean;
  labels: {
    appBug: string[];
    agentBug: string[];
  };
}

export interface GitHubIssue {
  owner: string;
  repo: string;
  title: string;
  body: string;
  labels: string[];
}

export class BugReporter {
  constructor(private config: ReporterConfig) {}

  async reportAppBug(bug: DetectedBug): Promise<string | null> {
    if (!this.config.createIssues) {
      console.log('[BugReporter] Issue creation disabled, skipping');
      return null;
    }

    const issue = this.buildAppBugIssue(bug);
    return this.createIssue(issue);
  }

  async reportAgentBug(bug: DetectedBug): Promise<string | null> {
    if (!this.config.createIssues) {
      console.log('[BugReporter] Issue creation disabled, skipping');
      return null;
    }

    const issue = this.buildAgentBugIssue(bug);
    return this.createIssue(issue);
  }

  private buildAppBugIssue(bug: DetectedBug): GitHubIssue {
    const [owner, repo] = this.config.appRepo.split('/');

    const body = `## Bug Report (Auto-generated by Probe)

### Description
${bug.description}

### Severity
**${bug.severity.toUpperCase()}**

### Steps to Reproduce
${bug.reproductionSteps.map((s, i) => `${i + 1}. ${s}`).join('\n')}

### Expected Behavior
${bug.expectedBehavior}

### Actual Behavior
${bug.actualBehavior}

### Environment
- **URL:** ${bug.url}
- **Session ID:** ${bug.sessionId}
- **Timestamp:** ${bug.timestamp.toISOString()}

### Console Errors
\`\`\`
${bug.consoleErrors.length > 0 ? bug.consoleErrors.join('\n') : 'None'}
\`\`\`

### Network Errors
${bug.networkErrors.length > 0 ? bug.networkErrors.map(e => `- ${e.method} ${e.url}: ${e.status || e.error}`).join('\n') : 'None'}

---
*This issue was automatically generated by [Probe](https://github.com/consciousfounders/probe)*`;

    return {
      owner,
      repo,
      title: `[Probe] ${bug.title}`,
      body,
      labels: [...this.config.labels.appBug, `severity-${bug.severity}`],
    };
  }

  private buildAgentBugIssue(bug: DetectedBug): GitHubIssue {
    const [owner, repo] = this.config.agentRepo.split('/');

    const body = `## Agent Self-Improvement Report

### Description
${bug.description}

### Classification
This issue was self-detected by Probe and classified as an **agent bug** - a problem with the test agent itself, not the target application.

### Context
- **URL being tested:** ${bug.url}
- **Session ID:** ${bug.sessionId}
- **Timestamp:** ${bug.timestamp.toISOString()}
- **Confidence:** ${(bug.confidence * 100).toFixed(0)}%

### Expected Behavior
${bug.expectedBehavior}

### Actual Behavior
${bug.actualBehavior}

### Suggested Fix Areas
- Selector reliability
- Timing/wait conditions
- Error handling
- Recovery strategies

### Reproduction Steps
${bug.reproductionSteps.map((s, i) => `${i + 1}. ${s}`).join('\n')}

---
*This is a self-reported issue for the overnight builder to address.*`;

    return {
      owner,
      repo,
      title: `[Self-Report] ${bug.title}`,
      body,
      labels: [...this.config.labels.agentBug],
    };
  }

  private async createIssue(issue: GitHubIssue): Promise<string> {
    const labels = issue.labels.join(',');

    // Escape special characters in body for shell
    const escapedBody = issue.body.replace(/'/g, "'\\''");

    const command = `gh issue create --repo ${issue.owner}/${issue.repo} --title '${issue.title.replace(/'/g, "'\\''")}' --body '${escapedBody}' --label '${labels}'`;

    try {
      const { stdout } = await execAsync(command);
      const issueUrl = stdout.trim();
      console.log(`[BugReporter] Created issue: ${issueUrl}`);
      return issueUrl;
    } catch (error) {
      console.error('[BugReporter] Failed to create issue:', error);
      throw error;
    }
  }
}
